// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.edu.ufcg.embedded.roocodeduplication.domain;

import br.edu.ufcg.embedded.roocodeduplication.domain.Job;

privileged aspect Job_Roo_JavaBean {
    
    public float Job.getCod() {
        return this.cod;
    }
    
    public void Job.setCod(float cod) {
        this.cod = cod;
    }
    
}
